### ISSUE TITLE
KanBan Board

### ISSUE THREAD

**Issue by jonathanmunamire** [jonathanmunamire/Recipe-App#22]
This is the [Link](https://github.com/jonathanmunamire/Recipe-App/projects/1) to our Project

We're a group of 2 persons: @jonathanmunamire and @Ibnballo1

**Comment by Abenezer-Tilahun** [comment]
Hi @jonathanmunamire  @Ibnballo1 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️Good Job for provide the link to Kanban board.
✔️ Good Job for mention how many people are in your Group
✔️ Good job for Implemented RoR group project: set up your Kanban board.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jonathanmunamire** [comment]
Thanks for the review @Abenezer-Tilahun
